backend:
  name: github
  repo: MiquelAlvarez/AccountAble

media_folder: static/assets
public_folder: public

collections:
  - name: todos
    label: todos
    label_singular: todo
    folder: todos
    create: true
    fields:
     - { name: date, label: Date, widget: date }
     - { name: title, label: Title, widget: string }
     - { name: done, label: Done, widget: boolean, default: false, required: false }
     - { name: Goal, label: Goal, widget: relation, collection: goals, searchFields: [goal], valueField: goal, displayFields: [Goal]}
     
  - name: books
    label: books
    label_singular: book
    folder: books
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: topic, label: Topic, widget: select, options: ['design', 'ba', 'tech', 'productivity', 'creativity'] }
      - { name: description , label: Description, widget: text }
      - { name: read, label: Read, widget: boolean, default: false, required: false }
      - { name: Goal, label: Goal, widget: relation, collection: goals, searchFields: [goal], valueField: goal, displayFields: [Goal]}
  
  - name: goals
    label: goals
    label_singular: goal
    folder: goals
    create: true
    fields: 
      - { name: title, label: Goal, widget: string }
      - { name: done, label: Completed, widget: boolean, default: false, required: false }
