backend:
  name: MiquelAlvarez/AccountAble

media_folder: static/assets
public_folder: assets

collections:
  - name: accountable
    label: Accountable
    folder: accountable
    create: true
    fields:
     - { name: path, label: Path }
     - { name: date, label: Date, widget: date }
     - { name: title, label: Title }
     - { name: body, label: Body, widget: markdown }